comment: off
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2
        base: auto
    patch:
      default:
        target: auto
        threshold: 2
        base: auto
